const db = require('../config/db');
const catchAsync = require('../utils/catchAsync');
const AppError = require('../utils/appError');
exports.getMe = catchAsync(async (req,res)=>{const [[user]]=await db.execute('SELECT id,name,email,role,phone,is_active,created_at FROM users WHERE id=?',[req.user.id]);res.json({status:'success',data:{user}});});
exports.updateMe = catchAsync(async (req,res)=>{const {name,phone}=req.body;if(!name)return res.status(400).json({status:'fail',message:'Name is required'});await db.execute('UPDATE users SET name=?,phone=? WHERE id=?',[name,phone||null,req.user.id]);const [[user]]=await db.execute('SELECT id,name,email,role,phone FROM users WHERE id=?',[req.user.id]);res.json({status:'success',data:{user}});});
exports.getAddresses = catchAsync(async (req,res)=>{const [addresses]=await db.execute("SELECT * FROM addresses WHERE user_id=? AND type='shipping' ORDER BY id DESC",[req.user.id]);res.json({status:'success',data:{addresses}});});
exports.createAddress = catchAsync(async (req,res,next)=>{const {street_address,city,state,postal_code,country='India'}=req.body;if(!street_address||!city||!state||!postal_code)return next(new AppError('Complete address is required',400));const [result]=await db.execute("INSERT INTO addresses (user_id,type,street_address,city,state,postal_code,country) VALUES (?,'shipping',?,?,?,?,?)",[req.user.id,street_address,city,state,postal_code,country]);const [[address]]=await db.execute('SELECT * FROM addresses WHERE id=?',[result.insertId]);res.status(201).json({status:'success',data:{address}});});
exports.updateAddress = catchAsync(async (req,res,next)=>{const {street_address,city,state,postal_code,country='India'}=req.body;const [result]=await db.execute("UPDATE addresses SET street_address=?,city=?,state=?,postal_code=?,country=? WHERE id=? AND user_id=? AND type='shipping'",[street_address,city,state,postal_code,country,req.params.id,req.user.id]);if(!result.affectedRows)return next(new AppError('Address not found',404));res.json({status:'success',message:'Address updated'});});
exports.deleteAddress = catchAsync(async (req,res,next)=>{const [result]=await db.execute("DELETE FROM addresses WHERE id=? AND user_id=? AND type='shipping'",[req.params.id,req.user.id]);if(!result.affectedRows)return next(new AppError('Address not found',404));res.status(204).send();});
