-- Run after arthub.sql. Adds a fuller ArtHub catalogue without duplicating category names.
INSERT INTO categories (name, description) SELECT 'Paper & Journals', 'Sketchbooks, journals and quality paper' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Paper & Journals');
INSERT INTO categories (name, description) SELECT 'Drawing', 'Pencils, charcoal and pastels' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Drawing');
INSERT INTO categories (name, description) SELECT 'Tools & Essentials', 'Palettes, tools and studio essentials' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Tools & Essentials');
INSERT INTO categories (name, description) SELECT 'Oil Paints', 'Professional and student oil colour ranges' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Oil Paints');
INSERT INTO categories (name, description) SELECT 'Varnishes & Mediums', 'Protective varnishes and painting mediums' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Varnishes & Mediums');
INSERT INTO categories (name, description) SELECT 'Brushes', 'Round, flat, filbert and detail brushes' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Brushes');
INSERT INTO categories (name, description) SELECT 'Canvas & Boards', 'Stretched canvas, panels and painting boards' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Canvas & Boards');
INSERT INTO categories (name, description) SELECT 'Markers & Inks', 'Illustration markers and expressive inks' WHERE NOT EXISTS (SELECT 1 FROM categories WHERE name='Markers & Inks');

INSERT INTO products (seller_id, category_id, title, description, base_price)
SELECT s.id, c.id, 'Botanical Watercolour Set', 'A joyful set of artist watercolours for everyday painting.', 1495
FROM sellers s JOIN categories c ON c.name='Paints' WHERE s.is_approved=TRUE AND NOT EXISTS (SELECT 1 FROM products WHERE title='Botanical Watercolour Set');
INSERT INTO products (seller_id, category_id, title, description, base_price)
SELECT s.id, c.id, 'The Everyday Sketchbook', 'Lay-flat sketchbook with warm white, 120 gsm paper.', 780
FROM sellers s JOIN categories c ON c.name='Paper & Journals' WHERE s.is_approved=TRUE AND NOT EXISTS (SELECT 1 FROM products WHERE title='The Everyday Sketchbook');
INSERT INTO products (seller_id, category_id, title, description, base_price)
SELECT s.id, c.id, 'Soft Pastels — Garden', 'A curated garden-toned set of velvety soft pastels.', 1890
FROM sellers s JOIN categories c ON c.name='Drawing' WHERE s.is_approved=TRUE AND NOT EXISTS (SELECT 1 FROM products WHERE title='Soft Pastels — Garden');

-- Oil colour, varnish, brush, canvas and drawing ranges
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Camlin Artist Oil Colours — 12 Set','Rich, buttery artist oil colours in a practical 12-tube set.',1195 FROM sellers s JOIN categories c ON c.name='Oil Paints' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Camlin Artist Oil Colours — 12 Set');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Winsor & Newton Winton Oil — Titanium White','A dependable, high-opacity white for oils and blends.',760 FROM sellers s JOIN categories c ON c.name='Oil Paints' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Winsor & Newton Winton Oil — Titanium White');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Daler-Rowney Georgian Oil Colour Set','Ten vibrant oil shades for studio landscapes and portraits.',2490 FROM sellers s JOIN categories c ON c.name='Oil Paints' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Daler-Rowney Georgian Oil Colour Set');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Liquitex Gloss Varnish','A clear, non-yellowing protective finish for acrylic paintings.',1380 FROM sellers s JOIN categories c ON c.name='Varnishes & Mediums' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Liquitex Gloss Varnish');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Camel Picture Varnish','Classic protective varnish for finished oil paintings.',420 FROM sellers s JOIN categories c ON c.name='Varnishes & Mediums' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Camel Picture Varnish');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Winsor & Newton Liquin Original','Fast-drying medium that improves flow and reduces brush marks.',1090 FROM sellers s JOIN categories c ON c.name='Varnishes & Mediums' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Winsor & Newton Liquin Original');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Princeton Select Round Brushes — 5 Pack','Responsive synthetic round brushes for detail and wash work.',980 FROM sellers s JOIN categories c ON c.name='Brushes' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Princeton Select Round Brushes — 5 Pack');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Camlin Flat Hog Brush Set','Natural bristle flats made for oils, acrylics and texture.',545 FROM sellers s JOIN categories c ON c.name='Brushes' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Camlin Flat Hog Brush Set');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Raphael SoftAqua Filbert Brush No. 8','Ultra-soft synthetic filbert with a generous water reservoir.',890 FROM sellers s JOIN categories c ON c.name='Brushes' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Raphael SoftAqua Filbert Brush No. 8');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Mont Marte Detail Brush Set','Fine liners and rounds for miniature detail and lettering.',680 FROM sellers s JOIN categories c ON c.name='Brushes' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Mont Marte Detail Brush Set');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Mungyo Gallery Soft Pastels — 48','Silky, blendable pastels in a wide spectrum of colours.',2150 FROM sellers s JOIN categories c ON c.name='Drawing' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Mungyo Gallery Soft Pastels — 48');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Faber-Castell Oil Pastels — 24','Creamy oil pastels with bright colour laydown.',680 FROM sellers s JOIN categories c ON c.name='Drawing' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Faber-Castell Oil Pastels — 24');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Sennelier Oil Pastels — Primary Set','Professional artist pastels with exceptionally rich pigment.',4650 FROM sellers s JOIN categories c ON c.name='Drawing' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Sennelier Oil Pastels — Primary Set');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Mont Marte Stretched Canvas — 12 × 16','Triple-primed cotton canvas ready for acrylic or oil.',560 FROM sellers s JOIN categories c ON c.name='Canvas & Boards' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Mont Marte Stretched Canvas — 12 × 16');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Canson XL Mixed Media Pad','Heavyweight textured pages for wet and dry experiments.',925 FROM sellers s JOIN categories c ON c.name='Paper & Journals' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Canson XL Mixed Media Pad');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Sakura Pigma Micron Fineliner Set','Archival black ink pens in six essential nib sizes.',1390 FROM sellers s JOIN categories c ON c.name='Markers & Inks' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Sakura Pigma Micron Fineliner Set');
INSERT INTO products (seller_id, category_id, title, description, base_price) SELECT s.id,c.id,'Copic Ciao Skin Tone Set','Blendable alcohol markers for illustration and character work.',3290 FROM sellers s JOIN categories c ON c.name='Markers & Inks' WHERE s.is_approved=TRUE AND NOT EXISTS(SELECT 1 FROM products WHERE title='Copic Ciao Skin Tone Set');

INSERT INTO inventory (product_id, sku, stock)
SELECT p.id, CONCAT('AH-', p.id), 25 FROM products p WHERE NOT EXISTS (SELECT 1 FROM inventory i WHERE i.product_id=p.id);

INSERT INTO product_images (product_id, image_url, is_primary)
SELECT p.id, 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=900&q=85', TRUE FROM products p WHERE p.title='Botanical Watercolour Set' AND NOT EXISTS (SELECT 1 FROM product_images WHERE product_id=p.id);
INSERT INTO product_images (product_id, image_url, is_primary)
SELECT p.id, 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=900&q=85', TRUE FROM products p WHERE p.title='The Everyday Sketchbook' AND NOT EXISTS (SELECT 1 FROM product_images WHERE product_id=p.id);
INSERT INTO product_images (product_id, image_url, is_primary)
SELECT p.id, 'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=900&q=85', TRUE FROM products p WHERE p.title='Soft Pastels — Garden' AND NOT EXISTS (SELECT 1 FROM product_images WHERE product_id=p.id);
