import { useContext, useEffect, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { CartContext } from '../context/CartContext';
import { AuthContext } from '../context/AuthContext';
import { createOrder } from '../services/orderService';
import { getAddresses } from '../services/userService';
import { selectCashOnDelivery } from '../services/paymentService';

const Checkout = () => {
  const { cart, clearCart } = useContext(CartContext); const { user } = useContext(AuthContext); const navigate = useNavigate();
  const [addresses,setAddresses]=useState([]); const [selected,setSelected]=useState('new'); const [form,setForm]=useState({street_address:'',city:'',state:'',postal_code:''}); const [error,setError]=useState(''); const [submitting,setSubmitting]=useState(false);
  const [paymentMethod,setPaymentMethod]=useState('online');
  useEffect(()=>{if(user?.role==='buyer')getAddresses().then(r=>setAddresses(r.data.addresses||[])).catch(()=>{});},[user]);
  const total=cart.reduce((sum,item)=>sum+Number(item.base_price||0)*Number(item.quantity||1),0); const update=e=>setForm({...form,[e.target.name]:e.target.value});
  const submit=async e=>{e.preventDefault();setError('');if(!user){navigate('/login');return;}if(!cart.length)return setError('Your cart is empty.');if(cart.some(item=>!item.inventory_id))return setError('This display product cannot be checked out yet. Add a stocked catalogue product.');setSubmitting(true);try{const payload={items:cart.map(item=>({inventory_id:item.inventory_id,quantity:Number(item.quantity||1)}))};if(selected==='new')payload.shipping_address=form;else payload.shipping_address_id=selected;const response=await createOrder(payload);const orderId=response?.data?.orderId;if(!orderId)throw new Error('The order was created, but its confirmation could not be loaded.');if(paymentMethod==='cod')await selectCashOnDelivery(orderId);clearCart();navigate(`/order/${orderId}`);}catch(err){setError(err.response?.data?.message||err.message||'We could not place your order.');}finally{setSubmitting(false);}};
  return <section className="cart-page site-container"><p className="eyebrow">CHECKOUT</p><h1>Almost time to make.</h1><div className="cart-layout"><form className="checkout-form" onSubmit={submit}><h3>Delivery details</h3>{error&&<div className="alert alert-danger py-2">{error}</div>}{user&&addresses.length>0&&<div className="mb-3"><label className="form-label small">Choose a saved address</label><select className="form-select" value={selected} onChange={e=>setSelected(e.target.value)}><option value="new">Use a new address</option>{addresses.map(a=><option key={a.id} value={a.id}>{a.street_address}, {a.city} — {a.postal_code}</option>)}</select></div>}{selected==='new'&&<div className="checkout-fields"><input className="wide" name="street_address" value={form.street_address} onChange={update} placeholder="Street address" required/><input name="city" value={form.city} onChange={update} placeholder="City" required/><input name="state" value={form.state} onChange={update} placeholder="State" required/><input className="wide" name="postal_code" value={form.postal_code} onChange={update} placeholder="PIN code" required/></div>}<p className="small text-muted mt-2">A new checkout address is saved to your account automatically.</p><h3>Payment method</h3><label className="payment-option"><input type="radio" checked={paymentMethod==='online'} onChange={()=>setPaymentMethod('online')} name="payment"/> <span><b>Pay online</b><small className="d-block text-muted">Secure Razorpay checkout at the next step</small></span></label><label className="payment-option"><input type="radio" checked={paymentMethod==='cod'} onChange={()=>setPaymentMethod('cod')} name="payment"/> <span><b>Cash on delivery</b><small className="d-block text-muted">Pay when your order arrives</small></span></label><button className="btn-primary-art" disabled={submitting} type="submit">{submitting?'Placing order…':!user?'Log in to continue':paymentMethod==='cod'?'Place COD order':'Continue to payment'} <span>→</span></button></form><aside className="cart-summary"><p className="eyebrow">YOUR ORDER</p>{cart.length?cart.map((item,i)=><div key={`${item.id}-${i}`}><span>{item.title} × {item.quantity||1}</span><b>₹{(Number(item.base_price)*Number(item.quantity||1)).toLocaleString('en-IN')}</b></div>):<p>Your cart is empty. <Link to="/">Go shopping</Link></p>}<hr/><div className="cart-total"><span>Total</span><b>₹{total.toLocaleString('en-IN')}</b></div></aside></div></section>;
}; export default Checkout;
